create table product (
  productId integer generated by default as identity,
  productName varchar(255),
  productCategory varchar(255),
  productCondition varchar(255),
  productDescription varchar(255),
  productManufacturer varchar(255),
  productPrice double not null,
  productStatus varchar(255),
  unitInStock integer not null,
  primary key (productId)
);

INSERT INTO product VALUES (
  NULL,
  'FENDER SQUIER BULLET',
  'Instrument',
  'new',
  'Budget and comfortable guitar for any Fender lover',
  'Fender',
  200.0,
  'active',
  10
);

create table users(
  username varchar(50) not null primary key,
  password varchar(50) not null,
  enabled boolean not null);

INSERT INTO users VALUES ('admin', '{noop}nimda', 1);

create table authorities (
  username varchar(50) not null,
  authority varchar(50) not null,
  constraint fk_authorities_users foreign key(username) references users(username));
create unique index ix_auth_username on authorities (username,authority);

INSERT INTO authorities VALUES ('admin', 'ROLE_USER');